-- ============================================================
-- devices
-- One row per registered app installation.
-- UUID is generated by the app on first launch (stable identity).
-- FCM token is updated via onTokenRefresh when Firebase rotates it.
-- notify_at: null = receive notification at cron time (MVP default).
--   V2: cron runs hourly and only notifies devices whose notify_at matches.
-- ============================================================
CREATE TABLE IF NOT EXISTS devices (
  id         UUID        PRIMARY KEY,
  fcm_token  TEXT        NOT NULL,
  notify_at  TIME,
  user_id    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;

-- SELECT required by PostgREST: upsert uses RETURNING internally even without .select().
-- Cron reads all FCM tokens via the secret key (bypasses RLS).
-- INSERT/UPDATE open to the publishable key (MVP); see TODO.md V2 for Edge Function upgrade.
CREATE POLICY "device self-select"
  ON devices FOR SELECT USING (true);

CREATE POLICY "device self-register"
  ON devices FOR INSERT WITH CHECK (true);

CREATE POLICY "device self-update"
  ON devices FOR UPDATE USING (true) WITH CHECK (true);


-- ============================================================
-- user_preferences
-- One row per authenticated user, written/read via RLS (auth.uid() = user_id).
-- ============================================================
CREATE TABLE IF NOT EXISTS user_preferences (
  user_id     UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  preferences JSONB       NOT NULL DEFAULT '{}',
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user read own prefs"
  ON user_preferences FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "user write own prefs"
  ON user_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user update own prefs"
  ON user_preferences FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- digests
-- One row per region per date, shared across all users.
-- Cron writes once daily; app reads for its selected regions.
-- Eviction: cron deletes rows older than 7 days before writing.
-- PRIMARY KEY (region, date) already covers the main app query:
--   WHERE region = ANY($1) AND date = $2
-- No extra index needed — max ~56 rows (8 regions × 7 days).
-- ============================================================
CREATE TABLE IF NOT EXISTS digests (
  region      TEXT        NOT NULL,
  date        DATE        NOT NULL,
  payload     JSONB       NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (region, date)
);

ALTER TABLE digests ENABLE ROW LEVEL SECURITY;

-- Required: RLS default denies everything. This allows the app's
-- publishable key to SELECT. Secret key bypasses RLS — no write policy needed.
CREATE POLICY "public read"
  ON digests
  FOR SELECT
  USING (true);
